export const FETCH_REQUEST_STARTED = 'FETCH_REQUEST_STARTED';
export const FETCH_REQUEST_SUCCEEDED = 'FETCH_REQUEST_SUCCEEDED';
export const FETCH_REQUEST_FAILED = 'FETCH_REQUEST_FAILED';

export const FETCH_POST = 'FETCH_POST';
export const NEW_POST = 'NEW_POST';
